INFO 2019-01-15 22:28:03,956 basehttp 124 "GET / HTTP/1.1" 200 16286
INFO 2019-01-15 22:28:03,991 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-01-15 22:28:04,028 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2019-01-15 22:28:04,074 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
INFO 2019-01-15 22:28:04,080 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
WARNING 2019-01-15 22:28:04,124 log 228 Not Found: /favicon.ico
WARNING 2019-01-15 22:28:04,126 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 1982
INFO 2019-01-15 22:54:08,071 basehttp 124 "GET / HTTP/1.1" 200 16934
WARNING 2019-01-15 22:54:08,130 log 228 Not Found: /css/base/common.css
WARNING 2019-01-15 22:54:08,137 basehttp 124 "GET /css/base/common.css HTTP/1.1" 404 2586
WARNING 2019-01-15 22:54:08,134 log 228 Not Found: /css/base/reset.css
WARNING 2019-01-15 22:54:08,141 log 228 Not Found: /css/news/index.css
WARNING 2019-01-15 22:54:08,141 basehttp 124 "GET /css/base/reset.css HTTP/1.1" 404 2583
WARNING 2019-01-15 22:54:08,145 basehttp 124 "GET /css/news/index.css HTTP/1.1" 404 2583
WARNING 2019-01-15 22:54:08,152 log 228 Not Found: /css/base/side.css
WARNING 2019-01-15 22:54:08,164 basehttp 124 "GET /css/base/side.css HTTP/1.1" 404 2580
WARNING 2019-01-15 22:54:08,159 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-15 22:54:08,162 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-15 22:54:08,178 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-15 22:54:08,179 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-15 22:54:08,173 log 228 Not Found: /js/base/common.js
WARNING 2019-01-15 22:54:08,184 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-15 22:54:08,183 log 228 Not Found: /js/index.js
WARNING 2019-01-15 22:54:08,191 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-15 22:54:08,189 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-15 22:54:08,193 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-15 22:54:08,204 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-15 22:54:08,211 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-15 22:54:08,209 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-15 22:54:08,214 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-15 22:54:08,220 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-15 22:54:08,227 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-15 22:54:08,226 log 228 Not Found: /images/english.jpg
WARNING 2019-01-15 22:54:08,229 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-15 22:54:08,976 log 228 Not Found: /js/base/common.js
WARNING 2019-01-15 22:54:08,977 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-15 22:54:08,990 log 228 Not Found: /js/index.js
WARNING 2019-01-15 22:54:08,992 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
INFO 2019-01-16 08:22:27,588 basehttp 124 "GET / HTTP/1.1" 200 16934
WARNING 2019-01-16 08:22:27,691 log 228 Not Found: /css/base/reset.css
WARNING 2019-01-16 08:22:27,707 basehttp 124 "GET /css/base/reset.css HTTP/1.1" 404 2583
WARNING 2019-01-16 08:22:27,694 log 228 Not Found: /css/base/common.css
WARNING 2019-01-16 08:22:27,711 basehttp 124 "GET /css/base/common.css HTTP/1.1" 404 2586
WARNING 2019-01-16 08:22:27,698 log 228 Not Found: /css/news/index.css
WARNING 2019-01-16 08:22:27,713 basehttp 124 "GET /css/news/index.css HTTP/1.1" 404 2583
WARNING 2019-01-16 08:22:27,702 log 228 Not Found: /css/base/side.css
WARNING 2019-01-16 08:22:27,706 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 08:22:27,727 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-16 08:22:27,728 basehttp 124 "GET /css/base/side.css HTTP/1.1" 404 2580
WARNING 2019-01-16 08:22:27,722 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 08:22:27,735 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 08:22:27,738 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 08:22:27,749 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 08:22:27,746 log 228 Not Found: /js/index.js
WARNING 2019-01-16 08:22:27,758 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 08:22:27,756 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 08:22:27,765 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 08:22:27,763 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 08:22:27,771 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 08:22:27,781 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 08:22:27,791 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-16 08:22:27,790 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 08:22:27,805 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 08:22:27,810 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 08:22:27,812 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 08:22:28,226 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 08:22:28,227 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 08:22:28,236 log 228 Not Found: /js/index.js
WARNING 2019-01-16 08:22:28,238 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 08:22:28,254 log 228 Not Found: /favicon.ico
WARNING 2019-01-16 08:22:28,255 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2019-01-16 09:10:13,271 basehttp 124 "GET / HTTP/1.1" 200 17019
INFO 2019-01-16 09:10:13,330 basehttp 124 "GET /static/css/base/reset.css HTTP/1.1" 200 1427
INFO 2019-01-16 09:10:13,332 basehttp 124 "GET /static/css/base/common.css HTTP/1.1" 200 3498
INFO 2019-01-16 09:10:13,333 basehttp 124 "GET /static/css/news/index.css HTTP/1.1" 200 5500
INFO 2019-01-16 09:10:13,348 basehttp 124 "GET /static/css/base/side.css HTTP/1.1" 200 4428
WARNING 2019-01-16 09:10:13,361 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 09:10:13,371 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-16 09:10:13,369 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 09:10:13,377 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:10:13,375 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:10:13,386 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:10:13,395 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:10:13,408 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:10:13,404 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 09:10:13,410 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 09:10:13,418 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 09:10:13,423 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:10:13,428 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 09:10:13,439 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 09:10:13,443 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 09:10:13,444 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:10:13,447 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 09:10:13,451 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
INFO 2019-01-16 09:10:13,457 basehttp 124 "GET /static/images/wechat.jpg HTTP/1.1" 200 24527
WARNING 2019-01-16 09:10:13,476 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:10:13,479 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:10:17,400 log 228 Not Found: /course/course.html
WARNING 2019-01-16 09:10:17,402 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2644
WARNING 2019-01-16 09:10:31,592 log 228 Not Found: /course/course.html
WARNING 2019-01-16 09:10:31,595 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2644
INFO 2019-01-16 09:11:33,468 basehttp 124 "GET / HTTP/1.1" 200 17019
WARNING 2019-01-16 09:11:33,506 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 09:11:33,514 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-16 09:11:33,511 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 09:11:33,520 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:11:33,535 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:11:33,547 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:11:33,542 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 09:11:33,555 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 09:11:33,547 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 09:11:33,559 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:11:33,563 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:11:33,569 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:11:33,573 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 09:11:33,582 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 09:11:33,581 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 09:11:33,594 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-16 09:11:33,599 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 09:11:33,607 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:11:33,606 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:11:33,609 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:11:34,687 log 228 Not Found: /index.html
WARNING 2019-01-16 09:11:34,688 basehttp 124 "GET /index.html HTTP/1.1" 404 2559
WARNING 2019-01-16 09:11:38,179 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:11:38,180 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:11:38,980 log 228 Not Found: /course/course.html
WARNING 2019-01-16 09:11:38,982 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
INFO 2019-01-16 09:27:37,543 basehttp 124 "GET / HTTP/1.1" 200 17051
WARNING 2019-01-16 09:27:37,577 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 09:27:37,598 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:27:37,600 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 09:27:37,610 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
INFO 2019-01-16 09:27:37,606 basehttp 124 "GET /static/js/base/common.js HTTP/1.1" 200 223
INFO 2019-01-16 09:27:37,628 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 1510
WARNING 2019-01-16 09:27:37,646 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 09:27:37,656 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:27:37,656 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:27:37,665 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:27:37,653 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 09:27:37,671 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-16 09:27:37,663 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 09:27:37,677 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 09:27:37,690 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 09:27:37,692 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
INFO 2019-01-16 09:32:03,405 basehttp 124 "GET / HTTP/1.1" 200 17211
INFO 2019-01-16 09:32:03,466 basehttp 124 "GET /static/images/jichujiaochen.jpeg HTTP/1.1" 200 11286
INFO 2019-01-16 09:32:03,489 basehttp 124 "GET /static/images/python_gui.jpg HTTP/1.1" 200 24129
INFO 2019-01-16 09:32:03,492 basehttp 124 "GET /static/images/python_function.jpg HTTP/1.1" 200 27960
INFO 2019-01-16 09:32:03,518 basehttp 124 "GET /static/images/linux.jpg HTTP/1.1" 200 62189
INFO 2019-01-16 09:32:03,519 basehttp 124 "GET /static/images/python_web.jpg HTTP/1.1" 200 45717
INFO 2019-01-16 09:32:03,536 basehttp 124 "GET /static/images/python_advanced.jpg HTTP/1.1" 200 120059
INFO 2019-01-16 09:32:03,549 basehttp 124 "GET /static/images/english.jpg HTTP/1.1" 200 137605
INFO 2019-01-16 14:36:22,796 basehttp 124 "GET / HTTP/1.1" 200 16476
WARNING 2019-01-16 14:38:48,914 log 228 Not Found: /course/course.html
WARNING 2019-01-16 14:38:48,915 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
WARNING 2019-01-16 14:40:22,396 log 228 Not Found: /index.html
WARNING 2019-01-16 14:40:22,398 basehttp 124 "GET /index.html HTTP/1.1" 404 2559
INFO 2019-01-16 14:42:01,826 basehttp 124 "GET / HTTP/1.1" 200 16467
INFO 2019-01-16 14:42:03,146 basehttp 124 "GET / HTTP/1.1" 200 16467
INFO 2019-01-16 14:42:05,828 basehttp 124 "GET / HTTP/1.1" 200 16467
INFO 2019-01-16 14:42:08,942 basehttp 124 "GET / HTTP/1.1" 200 16467
ERROR 2019-01-16 14:42:38,950 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:42:38,963 basehttp 124 "GET / HTTP/1.1" 500 134793
ERROR 2019-01-16 14:42:41,270 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:42:41,283 basehttp 124 "GET / HTTP/1.1" 500 134645
ERROR 2019-01-16 14:42:47,026 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:42:47,041 basehttp 124 "GET / HTTP/1.1" 500 134645
ERROR 2019-01-16 14:43:09,995 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:43:10,018 basehttp 124 "GET / HTTP/1.1" 500 133766
WARNING 2019-01-16 14:43:21,160 log 228 Not Found: /blog/
WARNING 2019-01-16 14:43:21,163 basehttp 124 "GET /blog/ HTTP/1.1" 404 2544
ERROR 2019-01-16 14:43:26,115 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:43:26,126 basehttp 124 "GET / HTTP/1.1" 500 133631
ERROR 2019-01-16 14:44:08,548 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:44:08,564 basehttp 124 "GET / HTTP/1.1" 500 133766
INFO 2019-01-16 14:44:51,675 basehttp 124 "GET / HTTP/1.1" 200 16461
INFO 2019-01-16 14:44:53,382 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:44:53,403 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:44:53,413 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:44:53,418 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:44:53,411 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:44:53,424 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:53,425 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:44:53,430 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:44:53,423 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:44:53,437 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:53,438 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:44:53,436 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:44:53,439 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
WARNING 2019-01-16 14:44:53,456 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:44:53,458 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
INFO 2019-01-16 14:44:55,766 basehttp 124 "GET / HTTP/1.1" 200 16461
INFO 2019-01-16 14:44:56,477 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:44:56,497 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:44:56,503 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:44:56,502 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:44:56,508 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:56,517 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:44:56,523 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:44:56,522 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:44:56,534 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:44:56,528 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:44:56,536 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:56,533 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:44:56,537 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
INFO 2019-01-16 14:45:39,180 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:45:41,853 basehttp 124 "GET /doc/ HTTP/1.1" 200 7633
INFO 2019-01-16 14:45:41,874 basehttp 124 "GET /static/css/doc/docDownload.css HTTP/1.1" 200 2121
WARNING 2019-01-16 14:45:43,594 log 228 Not Found: /course/course.html
WARNING 2019-01-16 14:45:43,595 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
WARNING 2019-01-16 14:45:47,406 log 228 Not Found: /course/course.html
WARNING 2019-01-16 14:45:47,408 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
INFO 2019-01-16 14:45:56,999 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:45:57,857 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:45:58,373 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:45:58,392 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:45:58,398 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:45:58,397 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:45:58,408 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:45:58,405 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:45:58,414 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:45:58,413 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:45:58,421 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:45:58,420 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:45:58,429 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:45:58,436 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:45:58,437 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
INFO 2019-01-16 14:52:42,582 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:52:45,428 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:52:45,447 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:52:45,454 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:52:45,453 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:52:45,457 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:52:45,463 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:52:45,473 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:52:45,468 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:52:45,474 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:52:45,472 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:52:45,476 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
WARNING 2019-01-16 14:52:45,480 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:52:45,483 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:52:45,497 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:52:45,498 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
INFO 2019-01-16 14:52:49,077 basehttp 124 "GET /doc/ HTTP/1.1" 200 8836
INFO 2019-01-16 14:54:19,669 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:22,111 basehttp 124 "GET /doc/ HTTP/1.1" 200 5130
INFO 2019-01-16 14:54:38,895 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:45,367 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:46,406 basehttp 124 "GET /doc/ HTTP/1.1" 200 2889
INFO 2019-01-16 14:54:55,260 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:56,544 basehttp 124 "GET /doc/ HTTP/1.1" 200 8836
INFO 2019-01-16 15:00:09,355 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 15:00:10,444 basehttp 124 "GET /doc/ HTTP/1.1" 200 5127
INFO 2019-01-16 15:02:26,568 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 15:05:56,112 basehttp 124 "GET / HTTP/1.1" 200 16445
INFO 2019-01-16 15:05:57,410 basehttp 124 "GET /doc/ HTTP/1.1" 200 7510
INFO 2019-01-16 15:14:14,464 basehttp 124 "GET / HTTP/1.1" 200 16435
INFO 2019-01-16 15:14:16,012 basehttp 124 "GET /search/ HTTP/1.1" 200 12364
WARNING 2019-01-16 15:14:16,043 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 15:14:16,050 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:14:16,054 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:14:16,066 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
INFO 2019-01-16 15:14:16,059 basehttp 124 "GET /static/css/news/search.css HTTP/1.1" 200 2803
WARNING 2019-01-16 15:14:16,069 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:14:16,076 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
WARNING 2019-01-16 15:14:16,065 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 15:14:16,078 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 15:14:16,075 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 15:14:16,087 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2773
WARNING 2019-01-16 15:14:16,086 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 15:14:16,089 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:14:16,100 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:14:16,101 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:14:16,116 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:14:16,117 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:15:31,660 basehttp 124 "GET / HTTP/1.1" 200 16435
INFO 2019-01-16 15:15:32,519 basehttp 124 "GET /search/ HTTP/1.1" 200 12406
WARNING 2019-01-16 15:15:32,533 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 15:15:32,534 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:15:32,544 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:15:32,549 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:15:32,556 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:15:32,557 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:16:01,096 basehttp 124 "GET /search/ HTTP/1.1" 200 12406
WARNING 2019-01-16 15:16:01,114 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 15:16:01,115 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:16:01,123 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:16:01,129 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:16:01,134 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:16:01,138 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:16:05,588 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 15:16:05,612 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:16:05,619 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:16:05,618 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:16:05,623 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:52:53,501 basehttp 124 "GET / HTTP/1.1" 200 16435
WARNING 2019-01-16 15:52:55,068 log 228 Not Found: /users/login.html
WARNING 2019-01-16 15:52:55,069 basehttp 124 "GET /users/login.html HTTP/1.1" 404 2992
INFO 2019-01-16 15:53:47,801 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 15:53:49,206 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:53:52,614 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:54:23,468 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 15:54:24,755 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7483
INFO 2019-01-16 15:54:27,811 basehttp 124 "GET /users/register/ HTTP/1.1" 200 8153
WARNING 2019-01-16 15:54:27,832 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 15:54:27,834 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 15:56:52,200 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 15:56:53,375 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:56:53,412 basehttp 124 "GET /static/css/authPro/auth.css HTTP/1.1" 200 3286
INFO 2019-01-16 15:56:56,101 basehttp 124 "GET /users/register/ HTTP/1.1" 200 8206
WARNING 2019-01-16 15:56:56,122 log 228 Not Found: /users/css/authPro/auth.css
WARNING 2019-01-16 15:56:56,128 basehttp 124 "GET /users/css/authPro/auth.css HTTP/1.1" 404 3022
WARNING 2019-01-16 15:56:56,127 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 15:56:56,130 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 15:56:57,774 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:57:22,512 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:57:24,516 basehttp 124 "GET /users/register/ HTTP/1.1" 200 8216
WARNING 2019-01-16 15:57:24,532 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 15:57:24,534 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 15:58:15,568 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:58:18,135 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:58:28,567 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:58:32,509 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:59:34,306 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 16:04:44,713 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 16:04:45,905 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 16:04:46,673 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4506
WARNING 2019-01-16 16:04:46,698 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 16:04:46,699 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 16:04:47,586 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 16:04:50,280 basehttp 124 "GET /doc/ HTTP/1.1" 200 5099
INFO 2019-01-16 16:04:53,417 basehttp 124 "GET /course/ HTTP/1.1" 200 4192
WARNING 2019-01-16 16:04:53,442 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:04:53,446 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:04:53,446 basehttp 124 "GET /static/css/course/course.css HTTP/1.1" 200 1916
WARNING 2019-01-16 16:04:53,445 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:04:53,448 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
INFO 2019-01-16 16:04:56,892 basehttp 124 "GET /course/ HTTP/1.1" 200 4192
WARNING 2019-01-16 16:04:56,918 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:04:56,921 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 16:04:56,926 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:04:56,928 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:05:17,593 basehttp 124 "GET /course/ HTTP/1.1" 200 4192
WARNING 2019-01-16 16:05:17,619 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:05:17,620 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 16:05:17,629 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:05:17,630 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:05:21,575 basehttp 124 "GET /course/ HTTP/1.1" 200 7902
WARNING 2019-01-16 16:05:21,605 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:05:21,617 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 16:05:21,615 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:05:21,622 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:06:18,810 basehttp 124 "GET /course/ HTTP/1.1" 200 7922
INFO 2019-01-16 16:06:51,341 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:07:11,171 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:07:16,285 basehttp 124 "GET /doc/ HTTP/1.1" 200 5099
INFO 2019-01-16 16:07:40,050 basehttp 124 "GET /doc/ HTTP/1.1" 200 8809
INFO 2019-01-16 16:10:49,252 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:10:50,315 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:10:51,030 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:10:51,616 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
ERROR 2019-01-16 16:18:15,502 log 228 Internal Server Error: /one/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 347, in _setup
    self._wrapped = self._setupfunc()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")
ERROR 2019-01-16 16:18:15,536 basehttp 124 "GET /one/ HTTP/1.1" 500 262326
INFO 2019-01-16 16:19:04,832 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:19:08,645 basehttp 124 "GET / HTTP/1.1" 200 16415
ERROR 2019-01-16 16:19:19,736 log 228 Internal Server Error: /one/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 347, in _setup
    self._wrapped = self._setupfunc()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")
ERROR 2019-01-16 16:19:19,761 basehttp 124 "GET /one/ HTTP/1.1" 500 262330
INFO 2019-01-16 16:20:08,028 basehttp 124 "GET /one/ HTTP/1.1" 200 9
INFO 2019-01-16 16:21:25,524 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:33:03,590 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-16 16:33:04,214 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 16:33:04,240 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:33:04,246 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:33:04,245 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:33:04,249 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
WARNING 2019-01-16 16:33:07,982 log 228 Not Found: /doc/docDownload.html
WARNING 2019-01-16 16:33:07,983 basehttp 124 "GET /doc/docDownload.html HTTP/1.1" 404 2715
WARNING 2019-01-16 16:33:18,400 log 228 Not Found: /course/course.html
WARNING 2019-01-16 16:33:18,401 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2709
INFO 2019-01-16 16:33:23,897 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 16:33:23,914 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:33:23,922 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:33:23,929 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:33:23,934 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
WARNING 2019-01-16 16:33:26,570 log 228 Not Found: /course/course.html
WARNING 2019-01-16 16:33:26,570 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2709
INFO 2019-01-16 16:33:36,538 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:33:39,195 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:33:39,832 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:33:45,310 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:33:46,477 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-16 16:33:47,920 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 16:33:47,944 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:33:47,953 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:33:47,967 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:33:47,975 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
INFO 2019-01-16 16:34:50,258 basehttp 124 "GET /search/ HTTP/1.1" 200 12411
WARNING 2019-01-16 16:34:50,282 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:34:50,284 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:34:50,508 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:34:50,511 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
WARNING 2019-01-16 16:34:57,410 log 228 Not Found: /search/search.html
WARNING 2019-01-16 16:34:57,411 basehttp 124 "GET /search/search.html HTTP/1.1" 404 2648
INFO 2019-01-16 16:35:02,564 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:35:03,984 basehttp 124 "GET /search/ HTTP/1.1" 200 12411
WARNING 2019-01-16 16:35:04,008 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:35:04,015 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:35:04,014 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:35:04,022 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
INFO 2019-01-16 16:39:53,671 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:39:54,684 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 16:39:54,697 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 223
INFO 2019-01-16 16:39:56,594 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 16:39:58,122 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 16:39:59,113 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
WARNING 2019-01-16 17:12:34,441 log 228 Not Found: /register_test/
WARNING 2019-01-16 17:12:34,443 basehttp 124 "GET /register_test/ HTTP/1.1" 404 2636
WARNING 2019-01-16 17:13:41,219 log 228 Not Found: /register
WARNING 2019-01-16 17:13:41,222 basehttp 124 "GET /register HTTP/1.1" 404 2618
WARNING 2019-01-16 17:13:46,701 log 228 Not Found: /register/
WARNING 2019-01-16 17:13:46,704 basehttp 124 "GET /register/ HTTP/1.1" 404 2621
INFO 2019-01-16 17:14:00,487 basehttp 124 "GET /users/register_test/ HTTP/1.1" 200 4506
WARNING 2019-01-16 17:14:00,511 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 17:14:00,513 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3101
INFO 2019-01-16 17:14:08,867 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4506
WARNING 2019-01-16 17:14:08,889 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 17:14:08,890 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3101
INFO 2019-01-16 17:14:48,758 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:14:48,774 basehttp 124 "GET /static/images/captcha.png HTTP/1.1" 200 4296
INFO 2019-01-16 17:15:30,973 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:15:32,968 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 17:15:33,824 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 17:15:34,512 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-16 17:15:35,044 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 17:15:35,894 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 17:15:36,495 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 17:15:37,090 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 17:15:37,989 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
WARNING 2019-01-16 17:15:39,398 log 228 Forbidden (CSRF token missing or incorrect.): /users/login/
WARNING 2019-01-16 17:15:39,400 basehttp 124 "POST /users/login/ HTTP/1.1" 403 2508
INFO 2019-01-16 17:17:01,057 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
WARNING 2019-01-16 17:17:02,178 log 228 Forbidden (CSRF token missing or incorrect.): /users/register/
WARNING 2019-01-16 17:17:02,180 basehttp 124 "POST /users/register/ HTTP/1.1" 403 2508
INFO 2019-01-16 17:19:31,886 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:19:35,826 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:19:39,569 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 17:19:44,139 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 17:19:45,098 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:19:45,762 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
WARNING 2019-01-16 19:14:01,712 log 228 Not Found: /admin/
WARNING 2019-01-16 19:14:01,714 basehttp 124 "GET /admin/ HTTP/1.1" 404 2612
WARNING 2019-01-16 19:14:20,521 log 228 Not Found: /admin/
WARNING 2019-01-16 19:14:20,529 basehttp 124 "GET /admin/ HTTP/1.1" 404 2612
INFO 2019-01-16 19:14:22,909 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
INFO 2019-01-16 19:14:23,017 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1821
INFO 2019-01-16 19:14:23,092 basehttp 124 "GET /static/admin/css/login.css HTTP/1.1" 200 1203
INFO 2019-01-16 19:14:23,093 basehttp 124 "GET /static/admin/css/base.css HTTP/1.1" 200 16225
INFO 2019-01-16 19:14:23,100 basehttp 124 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17976
INFO 2019-01-16 19:14:23,106 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-01-16 19:14:23,127 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
INFO 2019-01-16 19:14:23,160 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
INFO 2019-01-16 19:14:33,537 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-16 19:14:33,587 basehttp 124 "GET /admin/ HTTP/1.1" 200 2580
INFO 2019-01-16 19:14:33,610 basehttp 124 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
INFO 2019-01-16 19:14:33,627 basehttp 124 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2019-01-16 19:14:33,636 basehttp 124 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-01-16 19:14:33,657 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2019-01-16 19:14:37,909 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-16 19:14:37,940 basehttp 124 "GET /admin/ HTTP/1.1" 200 2580
INFO 2019-01-16 19:15:25,048 basehttp 124 "GET /admin/ HTTP/1.1" 200 2580
INFO 2019-01-16 19:15:31,004 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 19:42:13,947 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-17 11:02:32,174 basehttp 124 "GET / HTTP/1.1" 200 16415
WARNING 2019-01-17 11:02:32,522 log 228 Not Found: /favicon.ico
WARNING 2019-01-17 11:02:32,524 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2733
INFO 2019-01-17 11:02:34,576 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-17 11:02:35,055 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-17 11:02:35,450 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-17 11:02:36,415 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-17 11:02:36,791 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-17 11:02:37,376 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-17 11:18:53,577 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-17 11:20:10,185 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-17 11:20:11,653 basehttp 124 "GET /doc/ HTTP/1.1" 200 7624
INFO 2019-01-17 11:20:27,240 basehttp 124 "GET /doc/ HTTP/1.1" 200 7624
INFO 2019-01-17 11:20:29,484 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-17 11:47:11,744 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-17 14:49:36,860 views 42 Image code: RIQZ
INFO 2019-01-17 14:49:36,872 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3095
INFO 2019-01-17 14:52:55,757 views 42 Image code: JLDN
INFO 2019-01-17 14:52:55,759 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3403
INFO 2019-01-17 14:55:22,599 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3355
INFO 2019-01-17 15:00:18,748 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 2980
INFO 2019-01-17 15:03:11,210 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3181
INFO 2019-01-17 15:04:23,986 views 42 Image code: OLJ6
INFO 2019-01-17 15:04:23,987 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3221
INFO 2019-01-17 15:05:48,087 views 42 Image code: CTSJ
INFO 2019-01-17 15:05:48,088 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3038
INFO 2019-01-17 15:08:23,148 views 42 Image code: FNEV
INFO 2019-01-17 15:08:23,150 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3532
INFO 2019-01-17 15:11:56,714 views 43 Image code: KA8D
INFO 2019-01-17 15:11:56,716 basehttp 124 "GET /image_code/123e4567-e89b-12d3-a456-426655440000/ HTTP/1.1" 200 3126
INFO 2019-01-17 15:15:28,888 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-17 16:45:56,890 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-17 16:46:01,029 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 16:46:01,080 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2604
WARNING 2019-01-17 16:46:01,109 log 228 Not Found: /image_codes/4d1d5d06-55b1-45c6-9cb0-7bf1b774d88b/
WARNING 2019-01-17 16:46:01,111 basehttp 124 "GET /image_codes/4d1d5d06-55b1-45c6-9cb0-7bf1b774d88b/ HTTP/1.1" 404 3051
WARNING 2019-01-17 16:46:02,323 log 228 Not Found: /image_codes/2063992f-01e1-403a-9814-4c58ffb5d8f6/
WARNING 2019-01-17 16:46:02,324 basehttp 124 "GET /image_codes/2063992f-01e1-403a-9814-4c58ffb5d8f6/ HTTP/1.1" 404 3051
INFO 2019-01-17 16:46:57,907 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 16:46:57,929 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
WARNING 2019-01-17 16:46:57,962 log 228 Not Found: /image_codes/b63e17b0-d82e-4c9e-895a-a530e2df4182/
WARNING 2019-01-17 16:46:57,964 basehttp 124 "GET /image_codes/b63e17b0-d82e-4c9e-895a-a530e2df4182/ HTTP/1.1" 404 3051
WARNING 2019-01-17 16:46:59,897 log 228 Not Found: /image_codes/d0378b1a-d89f-4945-b7d5-7ccc7e03b48c/
WARNING 2019-01-17 16:46:59,898 basehttp 124 "GET /image_codes/d0378b1a-d89f-4945-b7d5-7ccc7e03b48c/ HTTP/1.1" 404 3051
WARNING 2019-01-17 18:26:42,005 log 228 Not Found: /image_codes/4818b211-ea17-4b82-b3f9-84df7fb382a6/
WARNING 2019-01-17 18:26:42,007 basehttp 124 "GET /image_codes/4818b211-ea17-4b82-b3f9-84df7fb382a6/ HTTP/1.1" 404 3051
INFO 2019-01-17 18:27:16,291 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4517
INFO 2019-01-17 18:27:16,310 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
WARNING 2019-01-17 18:27:16,341 log 228 Not Found: /image_codes/05490b23-6dc8-4f1f-a3f7-24bf9ed7aa52/
WARNING 2019-01-17 18:27:16,345 basehttp 124 "GET /image_codes/05490b23-6dc8-4f1f-a3f7-24bf9ed7aa52/ HTTP/1.1" 404 3051
INFO 2019-01-17 18:31:19,269 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 18:31:19,349 views 43 Image code: ADPW
INFO 2019-01-17 18:31:19,350 basehttp 124 "GET /image_codes/8ad34b60-4d42-46f5-afb1-823a8c1d1b1d/ HTTP/1.1" 200 3420
INFO 2019-01-17 18:31:44,802 views 43 Image code: 5FMP
INFO 2019-01-17 18:31:44,803 basehttp 124 "GET /image_codes/a3fdacdd-1b68-4d0a-a3a4-f4979101ecd4/ HTTP/1.1" 200 3208
INFO 2019-01-17 18:31:46,657 views 43 Image code: AG3K
INFO 2019-01-17 18:31:46,660 basehttp 124 "GET /image_codes/70dbd4d6-2347-4deb-85f0-7f27ef2a9008/ HTTP/1.1" 200 2966
INFO 2019-01-17 18:36:30,011 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 18:36:30,082 views 43 Image code: GCR4
INFO 2019-01-17 18:36:30,084 basehttp 124 "GET /image_codes/c068f565-eb89-4457-9cc0-e15e344480f4/ HTTP/1.1" 200 3012
INFO 2019-01-17 18:41:03,199 views 43 Image code: 7E3E
INFO 2019-01-17 18:41:03,200 basehttp 124 "GET /image_codes/dce8e92d-062a-4615-a627-7a535b2ab121/ HTTP/1.1" 200 2708
INFO 2019-01-17 18:41:05,965 views 43 Image code: 9IGH
INFO 2019-01-17 18:41:05,966 basehttp 124 "GET /image_codes/c6dfbb69-a68b-42f7-b894-e7d370095451/ HTTP/1.1" 200 3231
INFO 2019-01-17 19:05:18,481 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 19:05:18,502 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2183
INFO 2019-01-17 19:05:18,562 views 45 Image code: KTRD
INFO 2019-01-17 19:05:18,564 basehttp 124 "GET /image_codes/2c9f7086-c820-4ddd-8954-3597559f1137/ HTTP/1.1" 200 3175
INFO 2019-01-17 19:05:29,161 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 19:05:29,181 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-17 19:05:29,219 views 45 Image code: YRXP
INFO 2019-01-17 19:05:29,222 basehttp 124 "GET /image_codes/b405fb24-8b5e-4b30-b7a6-f9be0afc1890/ HTTP/1.1" 200 3083
INFO 2019-01-17 19:06:52,110 basehttp 124 "GET /image_codes/6bd20de6-9563-4552-956c-fba0f0cdc162/ HTTP/1.1" 200 3225
INFO 2019-01-17 19:06:53,378 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 19:06:53,395 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-17 19:06:53,431 basehttp 124 "GET /image_codes/0da276cf-a41d-44d3-acfb-18421a2fb455/ HTTP/1.1" 200 3016
INFO 2019-01-17 19:06:56,643 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 19:06:56,688 basehttp 124 "GET /image_codes/641ca0d7-31ef-4ac2-ad12-5d7a6de88696/ HTTP/1.1" 200 2900
WARNING 2019-01-17 19:08:06,076 log 228 Forbidden (CSRF token missing or incorrect.): /users/register/
WARNING 2019-01-17 19:08:06,077 basehttp 124 "POST /users/register/ HTTP/1.1" 403 2508
INFO 2019-01-17 19:08:09,736 views 45 Image code: ASJT
INFO 2019-01-17 19:08:09,737 basehttp 124 "GET /image_codes/b16cbd80-ff8f-4fb0-b011-f4f5ba7975e3/ HTTP/1.1" 200 3000
INFO 2019-01-17 19:23:23,767 basehttp 124 "GET /username/python/ HTTP/1.1" 200 12
INFO 2019-01-17 19:23:31,006 basehttp 124 "GET /username/youkou/ HTTP/1.1" 200 12
INFO 2019-01-17 19:23:35,418 basehttp 124 "GET / HTTP/1.1" 200 16415
ERROR 2019-01-17 19:30:06,838 log 228 Internal Server Error: /username/python/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 91, in get
    return JsonResponse()
TypeError: __init__() missing 1 required positional argument: 'data'
ERROR 2019-01-17 19:30:06,864 basehttp 124 "GET /username/python/ HTTP/1.1" 500 74917
ERROR 2019-01-17 19:30:31,874 log 228 Internal Server Error: /username/python/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 91, in get
    return JsonResponse()
TypeError: __init__() missing 1 required positional argument: 'data'
ERROR 2019-01-17 19:30:31,884 basehttp 124 "GET /username/python/ HTTP/1.1" 500 74835
INFO 2019-01-17 19:31:09,857 basehttp 124 "GET /username/python/ HTTP/1.1" 200 34
INFO 2019-01-17 19:31:23,041 basehttp 124 "GET /username/pyvip/ HTTP/1.1" 200 33
INFO 2019-01-17 19:33:07,984 basehttp 124 "GET /username/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-17 19:33:16,311 basehttp 124 "GET /username/python/ HTTP/1.1" 200 72
INFO 2019-01-17 19:33:28,879 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-17 19:33:30,930 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4536
INFO 2019-01-17 19:33:30,948 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2183
INFO 2019-01-17 19:33:31,033 views 50 Image code: RCVD
INFO 2019-01-17 19:33:31,035 basehttp 124 "GET /image_codes/07feff72-693c-4a3c-bf66-4b096a1d6f04/ HTTP/1.1" 200 3185
INFO 2019-01-17 19:37:26,247 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 19:37:26,261 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2219
INFO 2019-01-17 19:37:26,318 views 50 Image code: R8NV
INFO 2019-01-17 19:37:26,319 basehttp 124 "GET /image_codes/304644f2-e88b-4fa3-862a-3656f64938e9/ HTTP/1.1" 200 3370
INFO 2019-01-17 19:37:33,758 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 19:37:33,772 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-17 19:37:33,806 views 50 Image code: BLVH
INFO 2019-01-17 19:37:33,811 basehttp 124 "GET /image_codes/4bc34aa0-f8e4-48f2-946c-88a569e92e9b/ HTTP/1.1" 200 3248
INFO 2019-01-17 19:39:12,359 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 19:39:12,376 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2349
INFO 2019-01-17 19:39:12,449 views 50 Image code: TYB5
INFO 2019-01-17 19:39:12,450 basehttp 124 "GET /image_codes/dfa2d07a-2d28-4154-b904-7ffeadc2bcc0/ HTTP/1.1" 200 3325
WARNING 2019-01-17 19:39:16,372 log 228 Not Found: /usernames/python/
WARNING 2019-01-17 19:39:16,373 basehttp 124 "GET /usernames/python/ HTTP/1.1" 404 3165
INFO 2019-01-17 19:40:03,671 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 19:40:03,688 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2348
INFO 2019-01-17 19:40:03,742 views 50 Image code: RBIR
INFO 2019-01-17 19:40:03,744 basehttp 124 "GET /image_codes/ec3fe52f-40f2-4255-bb65-5a0e449e9bcd/ HTTP/1.1" 200 3117
INFO 2019-01-17 19:40:08,123 basehttp 124 "GET /username/python/ HTTP/1.1" 200 72
INFO 2019-01-17 19:41:22,254 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 19:41:22,272 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2349
INFO 2019-01-17 19:41:22,327 views 50 Image code: ZBIM
INFO 2019-01-17 19:41:22,328 basehttp 124 "GET /image_codes/681824c1-6278-46db-9bf9-1f93ee2ec1f2/ HTTP/1.1" 200 3130
INFO 2019-01-17 19:41:26,973 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 19:44:17,982 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 19:44:17,999 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-17 19:44:18,035 views 50 Image code: PVMF
INFO 2019-01-17 19:44:18,040 basehttp 124 "GET /image_codes/bd14d660-7012-4be8-8ce7-9fa84094df0a/ HTTP/1.1" 200 3528
INFO 2019-01-17 19:44:24,838 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-17 19:44:32,148 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:00:58,029 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 20:00:58,045 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2665
INFO 2019-01-17 20:00:58,104 views 50 Image code: JBY9
INFO 2019-01-17 20:00:58,105 basehttp 124 "GET /image_codes/fc3b5e0d-3c19-4229-9e73-c22bceead248/ HTTP/1.1" 200 3290
INFO 2019-01-17 20:01:07,088 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:01:46,992 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 20:01:47,011 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2665
INFO 2019-01-17 20:01:47,061 views 50 Image code: NCFK
INFO 2019-01-17 20:01:47,063 basehttp 124 "GET /image_codes/afb718fc-a9a3-4159-9ab4-660e6d82d6cd/ HTTP/1.1" 200 3002
INFO 2019-01-17 20:02:16,171 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 20:02:16,203 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2665
INFO 2019-01-17 20:02:16,281 views 50 Image code: NYJW
INFO 2019-01-17 20:02:16,283 basehttp 124 "GET /image_codes/843b8710-ed09-43b8-8713-55f7e40465f0/ HTTP/1.1" 200 3342
INFO 2019-01-17 20:02:30,432 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-17 20:07:28,854 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 20:07:28,872 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-17 20:07:29,105 views 50 Image code: UVYQ
INFO 2019-01-17 20:07:29,106 basehttp 124 "GET /image_codes/ff60704b-e9b1-4a65-9754-1d96bbc37dce/ HTTP/1.1" 200 2937
INFO 2019-01-17 20:12:12,813 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4551
INFO 2019-01-17 20:12:12,827 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2665
INFO 2019-01-17 20:12:12,929 views 50 Image code: KW8H
INFO 2019-01-17 20:12:12,931 basehttp 124 "GET /image_codes/f4f7c1a5-fe1b-4ce3-8bfd-24eaea9d8366/ HTTP/1.1" 200 3485
INFO 2019-01-17 20:12:19,098 basehttp 124 "GET /usernames/youkou/ HTTP/1.1" 200 72
INFO 2019-01-17 20:12:24,685 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:12:28,894 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:12:38,068 basehttp 124 "GET /usernames/18811112222/ HTTP/1.1" 200 77
INFO 2019-01-17 20:26:24,281 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4605
INFO 2019-01-17 20:26:24,297 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 2665
INFO 2019-01-17 20:26:24,400 views 50 Image code: 7KBP
INFO 2019-01-17 20:26:24,401 basehttp 124 "GET /image_codes/42e529d9-d7c6-4d88-b6cc-113d939d4904/ HTTP/1.1" 200 2872
INFO 2019-01-17 20:26:33,888 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:29:15,375 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:29:17,243 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:29:19,103 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:32:50,712 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4663
INFO 2019-01-17 20:32:50,727 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 200 3570
INFO 2019-01-17 20:32:50,732 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-17 20:32:50,856 views 50 Image code: RGAJ
INFO 2019-01-17 20:32:50,857 basehttp 124 "GET /image_codes/c019b26c-9d6e-4972-bd0c-29e6fb62a7a1/ HTTP/1.1" 200 3080
INFO 2019-01-17 20:32:51,527 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4663
INFO 2019-01-17 20:32:51,614 views 50 Image code: PN89
INFO 2019-01-17 20:32:51,618 basehttp 124 "GET /image_codes/2bdf0a30-b2fa-4a8a-b38d-772ea326dca1/ HTTP/1.1" 200 3252
INFO 2019-01-17 20:32:55,502 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-17 20:33:00,871 basehttp 124 "GET /usernames/youkou/ HTTP/1.1" 200 72
INFO 2019-01-17 20:33:05,516 basehttp 124 "GET /usernames/youkou/ HTTP/1.1" 200 72
INFO 2019-01-17 20:33:09,603 basehttp 124 "GET /usernames/xxxxx/ HTTP/1.1" 200 71
